---
title: "NYC Restaurant Inspection Results"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
```

```{r import data, message=FALSE,echo=FALSE}
get_all_inspections = function(url) {
  all_inspections = vector("list", length = 0)
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size))) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1}
  all_inspections}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows()

nyc_inspections = 
  nyc_inspections %>%
  mutate(longitude = longitude,
         latitude = latitude,
         score = as.numeric(score))

  
```


Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot for Grade-A Japanese restaurants distribution in NYC

```{r}
nyc_inspections %>% 
  filter(!is.na(building),
         grade == "A",
         cuisine_description == "Japanese") %>%
  mutate(text_label = str_c("Grade: ", grade, '\nScore: ', score)) %>% 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    color = ~boro, text = ~text_label, alpha = 0.5, colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot for Grade-A Japanese restaurants' Scores in NYC

```{r}
nyc_inspections %>% 
  filter(!is.na(building),
         grade == "A",
         cuisine_description == "Japanese") %>%
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
```

### Barchart for numbers of Grade-A Japanese restaurants in different rgion

```{r}
nyc_inspections %>% 
  filter(!is.na(building),
         grade == "A",
         cuisine_description == "Japanese") %>% 
  group_by(boro) %>%
  summarize(number = n()) %>% 
  plot_ly(x = ~boro, y = ~number, color = ~boro, type = "bar",
          colors = "Set2")
```

